### ISSUE TITLE
wat the hecc builder

### ISSUE THREAD

**Issue by kot83** [loli-services/Lolis-Sharp#1]
just
a) ew, ```public static LoliServices.LoliClient LoliClient = new LoliClient();``` more like `using LoliServices;`
b) ```Request Req = await LoliServices.GetAstolfo();``` ew wtf what did I create the client for
c) should be `await LoliClient#GetTypeAsync(string type)` and `await LoliClient#GetTypesAsync()`

**Comment by kot83** [comment]
Additionally, the library should not be called Lolis-Sharp, use be good boye and use LolisSharp or LoliSharp

**Comment by kot83** [comment]
be consistent with the naming
first lolis-sharp
then lolis.cs
then lolisservicessharp

**Comment by xXBuilderBXx** [comment]
Already working on it and changing the name convention right now
